### ISSUE TITLE
--thread parameter not taken into account by the command (+ question on long reads)

### ISSUE THREAD

**Issue by SianaLarue** [W-L/deviaTE#17]
Hi,

I am using DeviaTE on LongRead sequences with custom library. I initially saw that there was a --preset parameter that allowed to modify the alignment parameters according to LR or SR. Seems like this parameter is no longer available. But I'm still interested in using the tool.

I have manage to install and run the pipeline, however, although I have specified the number of threads to use, it seems that only 1 is being used to generate the .fused files in the preparation step. Hence, this step is taking very long to be processed...

Here is my line of command: 
`deviaTE --library MCTE_clem.fasta --threads 12 --families BDGP_ZAM#LTR/Gypsy,con48_roo#LTR/Pao,con2_Doc4#LINE/Jockey,con14_F-element#LINE/Jockey --annotation dm6.ncbi.gff3 --single_copy_genes RpL32,piwi,Act5C --input_fq_dir` 

I have 2 questions here:
Why is the --thread parameter not being taken into account? Does this step exclusively run on one?
Can this pipeline deal with LR or is this the reason for the extensive time taken to finish the preparation step?

Sorry if these questions are very naive... I am nowhere near an expert in bioinformatic tools!

Regards,
Anaïs

**Comment by SianaLarue** [comment]
My bad, the server's python version was outdated and it was automatically installing the old version of deviaTE with no possibility to update it...

Sorry for the inconvinence!

**Comment by W-L** [comment]
Hi,
Apologies for the late reply, just got back from leave. Glad you managed to resolve the issue. The newest version is designed to allow the use of long reads. As you described, the `--preset` option is intended for that, with `--preset map-ont` for nanopore reads, or `--preset map-pb`/`--preset map-hifi` for pacbio data. This parameter simply gets passed to the read mapper minimap2.
Good luck for your analysis, please let me know if you run into any other issues.
