### ISSUE TITLE
--input_fq_dir contains .fq files

### ISSUE THREAD

**Issue by MaKuzman** [W-L/deviaTE#6]
I ran the program with the parameter --input_fq_dir /path/to/dirname
but the dirname contained .fq files instead of fastq . It would be a quick fix I guess to allow for fq as well otherwise it exits with an error.

**Comment by W-L** [comment]
Yes absolutely, thanks for pointing that out. I just released version `0.3.8`, which reads `.fastq` and `.fq`.
