### ISSUE TITLE
Idea for walkthrough: additional information on how to process paired reads

### ISSUE THREAD

**Issue by AnnaMariaL** [W-L/deviaTE#9]
Hi Lukas,

I have a minor comment: 

I use DeviaTE to estimate TE copy numbers on already mapped bam files. These bam files consist of paired reads that have been mapped in single read mode, but the input for the mapping algorithm was a concatenated .fq file with both read pairs (read1 and read2). Thus, the same read name occurs twice in these files.

For some of these files, DeviaTE works just fine while for others, I get an error message similar to what has been reported here in the issues sections: 

_... line 70, in
fam_strand = seg.reference_name + '+'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'_

I realized that when renaming the reads before mapping (read_1, read_2, ..., read_n) - this resolves the issue.
Maybe this would be good to point out in the walkthrough? I can imagine that some users do have paired read data (e.g., for polymorphism scans) that are also used for TE analysis with DeviaTE.

Best,
Anna

**Comment by W-L** [comment]
Hi Anna, 
Thanks for getting in touch and for the helpful suggestion! I will add a note in the walkthrough, and I also uploaded a little script to give fastq reads unique names, in case that might be useful for someone (example/rename_reads.py). 
I should probably look into the cause of the problem and fix that instead at some point. 

Hope everything is going well, please let me know if there's anything else I can help with!
Lukas

**Comment by W-L** [comment]
740061d7c93987440cf5965f85465359e87a3ea1
e9e9cc3e575f9ff79e7ccc0ba91946b3dba82ae4
